'use client';
import { FormEvent, useEffect, useState } from 'react';
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type Address={id:string;label:string;full_name:string;line1:string;city:string;state?:string;postal_code:string;country:string;is_default:boolean};
type Cart={subtotal:string; item_count:number; items:any[]};
type Rate={id:string;carrier:string;service:string;amount:number;estimated_days:string;free_shipping:boolean};
type Order={id:string;grand_total:string;status:string;payment_status:string};
export default function CheckoutPage(){
 const [cart,setCart]=useState<Cart|null>(null); const [addresses,setAddresses]=useState<Address[]>([]); const [selected,setSelected]=useState(''); const [rates,setRates]=useState<Rate[]>([]); const [rate,setRate]=useState<Rate|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({label:'Home',full_name:'Grace Young Customer',phone:'',line1:'123 Beauty Ave',line2:'',city:'Los Angeles',state:'CA',postal_code:'90001',country:'US',is_default:true});
 const token=()=>localStorage.getItem('gy_customer_token')||'';
 async function authFetch(url:string,opts:any={}){const t=token(); if(!t){window.location.href='/login'; throw new Error('login required')} return fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}})}
 async function load(){const [cartRes,addrRes]=await Promise.all([authFetch(`${API}/api/v1/commerce/cart`),authFetch(`${API}/api/v1/commerce/addresses`)]); const c=await cartRes.json(); const a=await addrRes.json(); setCart(c); setAddresses(a); const sid=a.find((x:Address)=>x.is_default)?.id||a[0]?.id||''; setSelected(sid); await loadRates(c, form);}
 async function loadRates(c=cart, address=form){const res=await authFetch(`${API}/api/v1/shipping/rates`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address, subtotal:c?.subtotal||0, item_count:c?.item_count||1})}); const json=await res.json(); if(res.ok){setRates(json.rates); setRate(json.rates[0]);}}
 useEffect(()=>{load().catch(e=>setMessage(String(e)))},[]);
 async function saveAddress(e:FormEvent){e.preventDefault(); const res=await authFetch(`${API}/api/v1/commerce/addresses`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const json=await res.json(); if(!res.ok){setMessage(json.detail||'Address failed');return} setAddresses([json,...addresses]); setSelected(json.id); setMessage('Address saved'); await loadRates(cart, form)}
 async function pay(){setBusy(true); setMessage(''); const chosen=rate||rates[0]; const body:any=selected?{shipping_address_id:selected}:{address:form}; if(chosen){body.shipping_rate_id=chosen.id; body.shipping_carrier=chosen.carrier; body.shipping_service=chosen.service; body.shipping_total=chosen.amount} const oRes=await authFetch(`${API}/api/v1/commerce/checkout/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const order=await oRes.json(); if(!oRes.ok){setBusy(false);setMessage(order.detail||'Checkout failed');return} const sRes=await authFetch(`${API}/api/v1/payments/stripe/checkout-session`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id:order.id})}); const session=await sRes.json(); if(!sRes.ok){setBusy(false);setMessage(session.detail||'Payment failed');return} window.location.href=session.checkout_url;}
 return <main className="commercePage checkoutReal"><a href="/cart">← Cart</a><h1>Checkout</h1>{message&&<div className="authNotice">{message}</div>}<div className="checkoutColumns"><section className="panelLike"><h2>1. Shipping address</h2>{addresses.length>0&&<label>Saved address<select value={selected} onChange={e=>setSelected(e.target.value)}>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} · {a.line1}, {a.city}</option>)}</select></label>}<form className="checkoutForm" onSubmit={saveAddress}>{Object.entries(form).filter(([k])=>k!=='is_default').map(([k,v])=><label key={k}>{k}<input value={String(v)} onChange={e=>setForm(prev=>({...prev,[k]:e.target.value} as any))}/></label>)}<button>Save address</button></form></section><section className="panelLike"><h2>2. Shipping method</h2>{rates.map(r=><label className="rateOption" key={r.id}><input type="radio" checked={rate?.id===r.id} onChange={()=>setRate(r)}/><span>{r.carrier} · {r.service}<small>{r.estimated_days} business days</small></span><b>{r.amount===0?'FREE':`$${r.amount.toFixed(2)}`}</b></label>)}<h2>3. Payment</h2><p>Stripe Checkout is used in production. Without Stripe keys, the system uses a safe mock payment return URL.</p><button className="checkoutButton" disabled={busy||!cart?.items?.length} onClick={pay}>{busy?'Redirecting...':'Pay with Stripe'}</button></section><aside className="summary"><h2>Order summary</h2><p>Items: {cart?.item_count||0}</p><p>Subtotal ${Number(cart?.subtotal||0).toFixed(2)}</p><p>Shipping {rate? rate.amount===0?'FREE':`$${rate.amount.toFixed(2)}`:'-'}</p><h2>Total ${((Number(cart?.subtotal||0))+(rate?.amount||0)).toFixed(2)}</h2></aside></div></main>
}
